### ISSUE TITLE
Building minitrace as a dynamic library

### ISSUE THREAD

**Issue by JuliusBrueggemann** [hrydgard/minitrace#35]
# Advantages of a shared library
Building minitrace as a shared library would allow a user to disable tracing by swapping the minitrace library with a variant that was built without `MTR_ENABLED` without needing to recompile or relink their project. It would also fix some issues like #33.

# Implementation
Since minitrace is built with CMake, this should be relatively simple to implement. CMake's [GenerateExportHeader](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html) module can automatically generate an export header for you, which defines the macros to export symbols (which is mostly needed on Windows, where symbols are hidden by default).

When minitrace is built as a static library, CMake simply defines these macros to be empty, so minitrace itself would not need any `#ifdef`s or similar to differentiate between static and shared linkage.

If this is something you would be interested in, I would be more than happy to send a PR your way.

**Comment by hrydgard** [comment]
I'm not really actively maintaining minitrace since I'm not currently using it actively, but I'm happy to merge pull requests that enable various new use cases. This all sounds reasonable.
