### ISSUE TITLE
thread_local is not work in Mingw64 toolchain

### ISSUE THREAD

**Issue by myseemylife** [hrydgard/minitrace#40]
hi~thx for this amazing project!
when use it in my project!  i found that the tid  in trace.json are all same!
toolchain: mingw64-x86_x64 gcc8.1.0 seh poxis,
after i changed minitrace.c to minitrace.cpp and __thread  to c++11 thread_local,the tid are correct in json.

**Comment by hrydgard** [comment]
Hm. Is there no way to get __thread to work with mingw? I don't want to change the project to C++, although I guess there isn't much reason these days...

**Comment by myseemylife** [comment]
> Hm. Is there no way to get __thread to work with mingw? I don't want to change the project to C++, although I guess there isn't much reason these days...

i agreed that change it to a cpp file is not a good option, may be someone can help us to find that why __thread is not work with mingw64 toolchain ,i'm a new fish to mingw64 yet!

**Comment by myseemylife** [comment]
@hrydgard  in mintrace.h,  if _WIN32 macro defined，__thread was defined to declspec(thread),which  make msvc compiler happy!   mingw64 toochain has defiend _WIN32,so  maybe gcc compiler just ignored the declspec(thread).

**Comment by myseemylife** [comment]
work done!just close it
