### ISSUE TITLE
Segfault in mtr_flush

### ISSUE THREAD

**Issue by DethRaid** [hrydgard/minitrace#9]
I'm trying to use minitrace to profile my application, but minitrace seems to have other ideas.

I'm making a renderer. My renderer's shutdown process is... complicated, so I'm trying to flush minitrace's profiler data every few frames. The first frame executes without trouble, but on the second frame I get a segfault at line 249 in minitrace.c. It looks like `strlen` is segfaulting - which the internet suggests could be because the string `raw->a_str` isn't null-terminated?

**Comment by hrydgard** [comment]
I'm wondering if this might have been solved by #12?

**Comment by DethRaid** [comment]
I believe that #12 does fix my issue, however I've been hacking on my renderer a lot and there's lots of problems that prevent me from really testing it. Imma keep using `minitrace` and let you know if I run into any more problems

**Comment by DethRaid** [comment]
Update: I fixed the other issues and I'm still getting a segfault, on line 255 of `minitrace.c`. Looks like the same one I had earlier

**Comment by DethRaid** [comment]
For reference, https://github.com/NovaMods/nova-renderer/blob/master/src/nova_renderer.cpp is how I'm currently using Minitrace (everything is in that file)

**Comment by hrydgard** [comment]
Unless strdup is defined to something really bizarre in your codebase, I don't see how we could get a crash at that line. If you have nne event of type MTR_ARG_TYPE_STRING_COPY then the a_str would have been strdup'd and would be a nice null-terminated string.

**Comment by DethRaid** [comment]
PR is accepted, closing this issue
